### PR TITLE
Enable vi keys

### PR DESCRIPTION
**Pull request by NoUseFreak**
Make vi/vim users happy :-)

### CODE REVIEW

**Comment by aksakalli** [comment]
`c`, `m`. `p` keys are already in use :confused:

what could be possible use cases for vi keys? Maybe we can implement our own bindings...

**Comment by ritiek** [comment]
@aksakalli IMO we only need <kbd>j</kbd> and <kbd>k</kbd>, for moving up and down through processes. Please correct me if I am wrong.

**Comment by NoUseFreak** [comment]
Looks like enabling the vi keys only implements a few keys, those to navigate in the list. It seems an addition to the arrow keys. So I don't see any conflict and no need to implement the same keys instead of just enabling the flag. 

https://github.com/chjj/blessed/blob/master/lib/widgets/list.js#L107

**Comment by NoUseFreak** [comment]
@aksakalli @ritiek I indeed intended this to only enable `j` and `k`.

**Pull request closed without merging**
