### PR TITLE
snapcraft: update to core22

### PR DESCRIPTION
**Pull request by mitchdz**
Tested this snap on Ubuntu 22.04.3.

Everything works right now except Disk usage.

### CODE REVIEW

**Comment by mitchdz** [comment]
Upon further testing, there's an issue with this snap build as it constantly polls disk usage which isn't allowed, therefore `journalctl` gets filled with lines like

```
Aug 10 21:11:11 light audit[3475869]: AVC apparmor="ALLOWED" operation="ptrace" class="ptrace" profile="snap.gtop.gtop" pid=3475869 comm="cat" requested_mask="read" denied_mask="read" peer="unconfined"
```

**Comment by aksakalli** [comment]
Hi @mitchdz,

Thanks for the contribution and trying to fix the broken snap builds. Could you also fix the broken badge link? I am not what is the replacement for this line:

https://github.com/aksakalli/gtop/blob/14c1dc3be71c80e18848db64423ce4fc0bfd3206/README.md?plain=1#L9

**Comment by mitchdz** [comment]
@aksakalli Sure, I'll take a look into that!

Also just fixed the issue with journalctl by just using `--classic` confinement for now. This also fixes not being able to read disk usage, so all `gtop` functionality remains the same.

I'd like to be able to get the app working with strict confinement but sounds like a future improvement kind of thing.

**Comment by mitchdz** [comment]
@aksakalli could you try looking in [https://snapcraft.io/gtop/publicise](https://snapcraft.io/gtop/publicise)? That link should have the badge code, but I don't have access to the namespace

**Comment by aksakalli** [comment]
> @aksakalli could you try looking in https://snapcraft.io/gtop/publicise? That link should have the badge code, but I don't have access to the namespace

thanks for the link, I merged #133 for that change.

> I'd like to be able to get the app working with strict confinement but sounds like a future improvement kind of thing.

Shall we merge it then?

**Pull request merged**
